.TH "main.c" 3 "Thu Mar 17 2016" "Version 1.00a" "Sublim Telegram" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.RI "\fIfonction main, se connecte au serveur et recupere les entrées client \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv)"

.PP
fonction main, se connecte au serveur et recupere les entrées client main, ouvre le serveur et se met en attente de connexions
.PP
main 
.PP
\fBParameters:\fP
.RS 4
\fIargc\fP 
.br
\fIargv\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
1 en cas d'echec, 0 sinon 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Sublim Telegram from the source code\&.
