.TH "msgToRoomStruct" 3 "Thu Mar 17 2016" "Version 1.00a" "Sublim Telegram" \" -*- nroff -*-
.ad l
.nh
.SH NAME
msgToRoomStruct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <server\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBroomName\fP"
.br
.ti -1c
.RI "char * \fBmsg\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* msg"

.SS "char* roomName"


.SH "Author"
.PP 
Generated automatically by Doxygen for Sublim Telegram from the source code\&.
