.TH "users" 3 "Thu Mar 17 2016" "Version 1.00a" "Sublim Telegram" \" -*- nroff -*-
.ad l
.nh
.SH NAME
users \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <server\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "int \fBsz\fP"
.br
.ti -1c
.RI "int \fBsocks\fP [10]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* name"

.SS "int socks[10]"

.SS "int sz"


.SH "Author"
.PP 
Generated automatically by Doxygen for Sublim Telegram from the source code\&.
